//TypeWriter Effect
new TypeIt("#simpleUsage", {
  speed: 100,
  startDelay: 500,
  waitUntilVisible: true,
  loop: true
})
  .type("hello...")
  .pause(3000)
  .delete()
  .pause(1000)
  .type("s c r e e n s a v e r")
  .pause(1000)
  .delete()
  .pause(1000)
  .type("<3 bts")
  .pause(1000)
  .type(".")
  .move(-1)
  .delete(1)
  .type("t")
  .move(-5)
  .delete(1)
  .type("F")
  .move(-2)
  .delete(1)
  .type("I")
  .pause(1000)
  .delete(1)
  .move(8)
  .delete()
  .type("please input text here...")
  .pause(1000)
  .delete()
  .pause(1000)
  .type("pro scripting")
  .pause(1000)
  .delete()
  .pause(1000)
  .go();
